### ISSUE TITLE
how use username and password

### ISSUE THREAD

**Issue by littleweb** [mattcg/socks5-http-client#15]
how use username and password

**Comment by shiny** [comment]
+1

**Comment by kxjhcs** [comment]
+1

**Comment by m7ov** [comment]
+1

**Comment by mattcg** [comment]
I get it :)

This is coming soon.

**Comment by mattcg** [comment]
Will you try the master branch? It uses a new version of `socks5-client` that supports username and password authentication via the `socksUsername` and `socksPassword` options.

**Comment by Rafase282** [comment]
@mattcg I got this error when trying to use socks5 with request:

```err
Error: SOCKS authentication failed. Unexpected SOCKS authentication method: 255.
    at Socket.<anonymous> (/home/ubuntu/workspace/node_modules/socks5-client/lib/Socket.js:165:12)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20) 
```

**Comment by mattcg** [comment]
@Rafase282 thanks for testing. That's strange because 255 means "no acceptable authentication methods", which should produce a different error message.

- When you run `npm list`, what version of `socks5-client` does it report you're using?
- What SOCKS server are you using?

**Comment by Rafase282** [comment]
@mattcg 

```
├─┬ socks5-http-client@1.0.2
│ └─┬ socks5-client@1.1.2
│   └─┬ ip-address@4.2.0
│     ├─┬ cli@0.6.6
│     │ ├── exit@0.1.2
│     │ └─┬ glob@3.2.11
│     │   └─┬ minimatch@0.3.0
│     │     ├── lru-cache@2.7.3
│     │     └── sigmund@1.0.1
```

The socks server is 5 and for the host I can't disclose that information.

**Comment by mattcg** [comment]
@Rafase282 can you run npm update? socks5-client should be at least 1.2.0.

**Comment by Rafase282** [comment]
It is still on 1.1.2 my json has "socks5-http-client": "^1.0.2"

**Comment by mattcg** [comment]
Ah, can you change it to depend on `master` until release? I haven't bumped the version yet. Change it to `"socks5-http-client": "mattcg/socks5-http-client"`.

**Comment by Rafase282** [comment]
I get 

```
{
  "code": "InternalError",
  "message": "Invalid data, chunk must be a string or buffer, not object"
}
``` 
but no error on the server which I guess is fine, I'll just have to figure out how to solve that.

Thanks a lot. 
By any chance, is there a way to specify the type of socks? I think this is only for socks5 but it doesnt hurt to ask.

**Comment by mattcg** [comment]
@Rafase282 there was a bug in socks5-client causing that, which I've just fixed. Please run npm update again and re-test!

**Comment by Rafase282** [comment]
@mattcg somehow it just loads forever when i test with postman.

**Comment by Jevin23** [comment]
i receive error
Error: SOCKS authentication failed. Unexpected number of bytes received.
data = {"type":"Buffer","data":[5,2,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

**Comment by Tehnorg** [comment]
fix authentification

**Comment by Tehnorg** [comment]
socks5-client

**Comment by Tehnorg** [comment]
Thank you. I did  the update, all works fine.

2016-11-16 12:07 GMT+02:00 Matthew Caruana Galizia <notifications@github.com

**Comment by mattcg** [comment]
✨ thank you @Tehnorg !

**Comment by Tehnorg** [comment]
You welcom. Thanks for nice library.

2016-11-16 14:19 GMT+02:00 Matthew Caruana Galizia <notifications@github.com

**Comment by TheGP** [comment]
So where how to use auth in docs?

**Comment by mattcg** [comment]
> So where how to use auth in docs?

It's described in the Options section of the README.
