### ISSUE TITLE
npm WARN deprecated minimatch@0.3.0

### ISSUE THREAD

**Issue by shiny** [mattcg/socks5-http-client#19]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
![image](https://cloud.githubusercontent.com/assets/117487/16497308/c8606216-3f28-11e6-90e1-b5f307293263.png)

**Comment by mattcg** [comment]
Hi @shiny, thanks for filing this. The problem is that mochajs/mocha is referencing an outdated version of minimatch. See: mochajs/mocha/pull/2325. There's nothing to do but wait for them to fix it.
