### ISSUE TITLE
NPM outdated dependency

### ISSUE THREAD

**Issue by Desuuuu** [mattcg/socks5-http-client#22]
Could you please publish an update of this package to NPM with the socks5-client dependency updated?

Reading #15 I'm guessing that it would fix:

`Error: SOCKS authentication failed. Unexpected SOCKS authentication method: 255.`

Currently the npm package installs `socks5-client@1.1.2` which I believe is causing the error.

**Comment by gonzalobarria** [comment]
Yes please!!... I'm waiting for it

**Comment by lorem--ipsum** [comment]
Same here :)

**Comment by mattcg** [comment]
Done.
