### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by KagamiChan** [mattcg/socks5-http-client#25]
Hi, as I've pointed out at https://github.com/mattcg/socks5-http-client/pull/24#issuecomment-397024827, the merged PR is not shipped yet. As the current version introduces unnecessary dependencies as well as npm audit reports, It will be of great help if the package on npm could be updated.

**Comment by mattcg** [comment]
Published!

**Comment by KagamiChan** [comment]
Much appreciated
