### ISSUE TITLE
SOCKS connection failed. Connection refused

### ISSUE THREAD

**Issue by raitucarp** [mattcg/socks5-http-client#7]
I got this:
```
Error: SOCKS connection failed. Connection refused.
    at Socket.socket.ondata (/home/apps/test/node_modules/socks5-http-client/node_modules/socks5-client/lib/socket.js:193:12)
    at TCP.onread (net.js:527:27)
```

what is that?

**Comment by kennysmoothx** [comment]
The example application tor.js gives this exact issue.

```
problem with request: connect ECONNREFUSED
```

I'm not able to get this to work in any way

**Comment by mattcg** [comment]
@kennysmoothx what node version are you using and on what OS?

**Comment by kennysmoothx** [comment]
node version `v0.10.29`

Have tried this on Max OSX & CentosOS

**Comment by mattcg** [comment]
Working fine here. Are you sure you have the Tor server running locally? The example attempts to the default port, on 9050.
